#!/bin/bash
#
# EZ Installer. Run from the bash command line:
#
#    curl -L https://raw.githubusercontent.com/gitbls/sdm/master/EZsdmInstaller | bash
#
# Installs into /usr/local/sdm by default
# If you specify a different directory (first argument), it assumes that sudo is not required
#

[ "$1" != "" ] && dir="$1" || dir="/usr/local/sdm"

src="https://github.com/gitbls/sdm/raw/master"
[ "$dir" == "/usr/local/sdm" ] && sudo="sudo" || sudo=""

$sudo mkdir -p $dir $dir/1piboot

for f in sdm sdm-phase0 sdm-phase1 sdm-cparse \
	     sdm-firstboot sdm-apt-cacher sdm-apt \
	     sdm-customphase sdm-apps-example sdm-xapps-example \
	     1piboot/1piboot.conf \
	     1piboot/010-disable-triggerhappy.sh \
	     1piboot/030-disable-rsyslog.sh
do
    $sudo curl -L $src/$f -o $dir/$f
done

$sudo chmod -R 755 $dir/*
$sudo chmod 644 $dir/{sdm-apps-example,sdm-xapps-example} $dir/1piboot/1piboot.conf

if [ "$dir" == "/usr/local/sdm" ]
then
    if ! $sudo dpkg-query -s systemd-container > /dev/null 2>&1
    then
	echo " Installing systemd-container"
	$sudo apt install systemd-container --no-install-recommends
    else
	echo " Great! systemd-container is already installed"
    fi
    echo "Invoke sdm with 'sudo $dir/sdm'"
else
    echo ""
    echo "You can inspect sdm in $1..."
    echo "To use sdm:"
    echo "  Rerun this script and install into /usr/local/sdm"
    echo "   or move the contents of $dir to /usr/local/sdm"
    ! dpkg-query -s systemd-container > /dev/null 2>&1 && echo "   'sudo apt install systemd-container --no-install-recommends'"
fi


