#!/bin/bash
#
# $1 has the message
#
# Prefix path to history log if we've been run from phase 0
# Otherwise, we're in the nspawn so prefix not required
#
# THIS SCRIPT IS NO LONGER NEEDED.
[[ "$0" =~ "/mnt/sdm" ]] && m="/mnt/sdm" || m=""
source $m/usr/local/sdm/sdm-cparse ; readparams $m
[ ! -f "$m/etc/sdm/history" ] && touch $m/etc/sdm/history
echo "$(date +"$datefmt") $1" >> $m/etc/sdm/history
