#!/bin/bash

#
# raspi-config do_vnc implementation only works if wayfire is running, but it's not during firstboot
# So, copy the code here and do it here. 
#
function enable_wayvnc() {

    HOMEDIR="/home/$myuser"
    systemctl --now disable vncserver-x11-serviced.service > /dev/null 2>&1
    mkdir -p $HOMEDIR/.config/wayvnc
    if ! [ -e $HOMEDIR/.config/wayvnc/config ]
    then
        cat << EOF > $HOMEDIR/.config/wayvnc/config
use_relative_paths=true
address=0.0.0.0
enable_auth=true
enable_pam=true
private_key_file=key.pem
certificate_file=cert.pem
rsa_private_key_file=rsa_key.pem
EOF
      fi
    if ! [ -e $HOMEDIR/.config/wayvnc/key.pem ] || ! [ -e $HOMEDIR/.config/wayvnc/cert.pem ]
    then
        logger "FirstBoot: Generate wayvnc keys..."
        HOSTNAME=$(cat /etc/hostname)
        IP=$(ifconfig | grep inet | head -n 1 | cut -d ' ' -f 10)
        openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes -keyout $HOMEDIR/.config/wayvnc/key.pem -out $HOMEDIR/.config/wayvnc/cert.pem -subj /CN=$HOSTNAME -addext subjectAltName=DNS:$HOSTNAME,DNS:$HOSTNAME,IP:$IP 2> /dev/null
      fi
    if ! [ -e $HOMEDIR/.config/wayvnc/rsa_key.pem ]
    then
        logger "FirstBoot: Generate wayvnc RSA key..."
        ssh-keygen -m pem -f $HOMEDIR/.config/wayvnc/rsa_key.pem -t rsa -N "" > /dev/null
      fi
      KBL=$(grep XKBLAYOUT /etc/default/keyboard | cut -d \" -f 2)
      KBV=$(grep XKBVARIANT /etc/default/keyboard | cut -d \" -f 2)
      if [ -z $KBV ]
      then
          VNCKBD="$KBL"
      else
          VNCKBD="$KBL-$KBV"
      fi
      cat << EOF > /etc/xdg/autostart/wayvnc.desktop
[Desktop Entry]
Type=Application
Name=wayvnc
Comment=Start wayvnc
NoDisplay=true
Exec=/usr/bin/wayvnc --render-cursor --keyboard=$VNCKBD
OnlyShowIn=wayfire
EOF
      chown -R $myuser:users $HOMEDIR/.config/wayvnc
}
