#!/bin/bash
#
# Copies personalization files into an SD card image
#

#
# Read configuration information from sdm (/etc/sdm/cparams)
#
source /mnt/sdm/usr/local/sdm/sdm-cparse ; readparams /mnt/sdm

logtoboth /mnt/sdm "* Start Phase 0 image customization"

logtoboth /mnt/sdm "> Set up ssh in boot partition"
logtoboth /mnt/sdm "> (wpa_supplicant.conf will be done later)"
touch /mnt/sdm/boot/ssh
#
# Set HDMI configuration if requested
#
if [ "$hdmigroup" != "" -a "$hdmimode" != "" ]
then
    logtoboth /mnt/sdm "> Set hdmigroup and hdmimode in /boot/config.txt configuration"
    sed -i "s/\#hdmi_group=1/hdmi_group=$hdmigroup/" /mnt/sdm/boot/config.txt
    sed -i "s/\#hdmi_mode=1/hdmi_mode=$hdmimode/" /mnt/sdm/boot/config.txt
fi
#
# Set other config.txt settings (if any)
#
if [ "$bootconfig" != "" ]
then
    logtoboth /mnt/sdm "> Update /boot/config.txt for bootconfig: $bootconfig"
    readarray -d, citems <<< $bootconfig
    for c in ${citems[@]}
    do
	IFS=":=" read key value <<< $c
	value="${value%,}"
	sed -i "s/\#$key=.*/$key=$value/" /mnt/sdm/boot/config.txt
	logtoboth /mnt/sdm ">  $key=$value"
    done
fi
if [ "$bootadd" != "" ]
then
    if ! grep -q 'Following items added by sdm --bootadd' /mnt/sdm/boot/config.txt
    then
	logtoboth /mnt/sdm "> Add new keys to /boot/config.txt"
	logtoboth /mnt/sdm "> Update /boot/config.txt for bootadd: $bootadd"
	echo "# Following items added by sdm --bootadd" >> /mnt/sdm/boot/config.txt
	readarray -d, citems <<< $bootadd
	for c in ${citems[@]}
	do
	    IFS=":=" read key value <<< $c
	    value="${value%,}"
	    echo "$key=$value" >> /mnt/sdm/boot/config.txt
	    logtoboth /mnt/sdm ">  $key=$value"
	done
	echo "# Above items added by sdm --bootadd" >> /mnt/sdm/boot/config.txt
    else
	logtoboth /mnt/sdm "> /boot/config.txt already updated for --bootadd; skipping"
    fi
fi
#
# Set up sdm-firstboot service. This service sets the wifi country and hostname
# on the first boot of the system. Other parameters (locale, keymap, timezone) are set
# in the nspawn
# Service will be enabled (by creating run.firstboot) when SD card is burned with sdm
#
logtoboth /mnt/sdm "> Set up sdm-firstboot service"
[ -f /mnt/sdm/etc/systemd/system/sdm-firstboot.service ] && rm -f /mnt/sdm/etc/systemd/system/sdm-firstboot.service
cat > /mnt/sdm/etc/systemd/system/sdm-firstboot.service <<EOF
[Unit]
Description=sdm System FirstBoot Configuration
After=network.target
Before=rc-local.service
ConditionPathExists=/usr/local/sdm/thispi/run.firstboot

[Service]
ExecStart=/usr/local/sdm/sdm-firstboot /usr/local/sdm/thispi/1piboot/1piboot.conf 1
ExecStartPost=/bin/rm /usr/local/sdm/thispi/run.firstboot
Type=oneshot
RemainAfterExit=no

[Install]
WantedBy=multi-user.target
EOF

[ ! -h /mnt/sdm/etc/systemd/system/multi-user.target.wants/sdm-firstboot.service ] && ln -s /etc/systemd/system/sdm-firstboot.service /mnt/sdm/etc/systemd/system/multi-user.target.wants/sdm-firstboot.service

if [ "$myuser" != "" ]
then
    #
    # do what we can now. Can't create the new user until nspawn. Done in sdm-phase1
    # home directory ownership fixed then as well
    #
    logtoboth /mnt/sdm "> Add '$myuser' to sudoers.d"
    echo "$myuser ALL=(ALL) NOPASSWD: ALL" > /mnt/sdm/etc/sudoers.d/010_$myuser-nopasswd
    chmod 440 /mnt/sdm/etc/sudoers.d/010_$myuser-nopasswd
    [ ! -d /mnt/sdm/home/$myuser ] && mkdir /mnt/sdm/home/$myuser
fi

if [ "$eeprom" != "" ]
then
    logtoboth /mnt/sdm "> Set rpi-eeprom to '$eeprom'"
    sed -i "s/critical/$eeprom/" /mnt/sdm/etc/default/rpi-eeprom-update
fi


if [ "$cscript" != "" ]
then
    logtoboth /mnt/sdm "> Run Custom Script '$cscript' Phase 0"
    $cscript 0
fi

logtoboth /mnt/sdm "* Phase 0 Completed"
