#!/bin/bash

source /usr/local/sdm/sdm-cparse
/usr/local/sdm/sdm-logit "sdm Install Base Applications Starting"
#
# Check for apt confirm
#
[ $aptconfirm -eq 1 ] && yes="" || yes="-y"

apt update

utils="keychain vim emacs dnsutils putty aptitude qpdfview avahi-utils python3-pip uuid-runtime lftp ncftp tmux mc iftop"
utils="$utils nfs-kernel-server whois telnet lsof iperf3 zip nmap feh links2 systemd-container zerofree"

echo "Installing important stuff ($utils)..."
apt install --no-install-recommends $yes $utils

echo "Performing apt upgrade..."
apt upgrade $yes

echo "Doing apt autoremove just in case..."
apt autoremove

/usr/local/sdm/sdm-logit "sdm Install Base Applications Completed"

