#!/bin/bash
#
# Sample sdm Custom Phase script
#
# $1 is the phase: "0", "1", or "post-install"

function doapt() {
    #
    # $1 is apt command (minus 'apt'. e.g., "install pkg1 pkg2")
    # $2 is $showapt value
    #
    # Executes the specified apt command and logs the output to the log file
    # If --showapt specified, the apt output is also displayed on the terminal
    # Can only be used in Phase 1
    #
    echo "" >> /etc/sdm/apt.log
    echo "** $1" >> /etc/sdm/apt.log
    echo "" >> /etc/sdm/apt.log
    if [ "$2" == "1" ]
    then
	apt -q $1 | tee -a /etc/sdm/apt.log
    else
	apt -q $1 >> /etc/sdm/apt.log
    fi
}
#
# Main code for the script
#
phase=$1
pfx="$(basename $0) Phase $phase"     #For messages
if [ $phase == "0" ]
then
    #
    # In Phase 0 all references to directories in the image
    # must be preceded by /mnt/sdm
    #
    source /mnt/sdm/usr/local/sdm/sdm-cparse
    echo ""
    echo "* Starting Custom Phase 0"
    /mnt/sdm/usr/local/sdm/sdm-logit "$pfx Phase 0 Starting"

    echo "  Copy wpa_supplicant.conf"
    /mnt/sdm/usr/local/sdm/sdm-logit "$pfx Copy wpa_supplicant.conf"
    #
    # You'll need to modify this to reflect the actual location of your wpa_supplicant.conf source
    #
    cp -f $csrc/etc/wpa_supplicant/wpa_supplicant.conf /mnt/sdm/boot
    # Can also copy to the specific device wpa_supplicant if desired
    cp -f $csrc/etc/wpa_supplicant/wpa_supplicant.conf /mnt/sdm/etc/wpa_supplicant/wpa_supplicant-wlan0.conf

    # Make directories for NFS mounting
#    for f in a b c d e f g h i j k l m n o p q r s t u v w x y z
#    do
#	[ ! -d /mnt/sdm/$f ] && mkdir /mnt/sdm/$f
#    done
    
#    echo "  Copy /usr/local/bin config scripts" 
#    /mnt/sdm/usr/local/sdm/sdm-logit "$pfx Copy /usr/local/bin config scripts"
    
#    for f in \
#		     wlanset \
#		     xdmset
#    do
#        cp -f $csrc/local/$f /mnt/sdm/usr/local/bin
#    done
    
    if [ "$myuser" != "" ]
    then
	echo "  Copy $myuser login files to /mnt/sdm/home/$myuser"
	/mnt/sdm/usr/local/sdm/sdm-logit "$pfx Copy $myuser login files to /mnt/sdm/home/$myuser"
	[ ! -d /mnt/sdm/home/$myuser ] && mkdir /mnt/sdm/home/$myuser   # Should be created in sdm-phase0, but just to be safe
	cp -f /home/$myuser/.bashrc /mnt/sdm/home/$myuser
    fi
    
#    echo "Copy systemd services (xvnc, iptables, wpaping)"
#    cp $csrc/systemd/*.service         /mnt/sdm/etc/systemd/system
#    cp $csrc/systemd/*.socket          /mnt/sdm/etc/systemd/system
#    cp $csrc/systemd/*.timer           /mnt/sdm/etc/systemd/system
#    cp $csrc/systemd/network/*.network /mnt/sdm/etc/systemd/network
#    [ -f /mnt/sdm/etc/systemd/timesyncd.conf ] && mv /mnt/sdm/etc/systemd/timesyncd.conf /mnt/sdm/etc/systemd/timesyncd.conf.orig
#    cp $csrc/systemd/timesyncd.conf /mnt/sdm/etc/systemd

    echo "* Custom Phase 0 Completed"
    /mnt/sdm/usr/local/sdm/sdm-logit "$pfx Phase 0 Completed"
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    # In Phase 1 all references to directories in the image can be direct
    #
    source /usr/local/sdm/sdm-cparse
    echo "* Starting Custom Phase 1"
    /usr/local/sdm/sdm-logit "$pfx Starting"

    echo "* Custom Phase 1 completed"
    /usr/local/sdm/sdm-logit "$pfx Completed"
else
    #
    # Post-install edits
    #
    source /usr/local/sdm/sdm-cparse
    echo "* Starting Custom Phase Post-Install configuration"
    /usr/local/sdm/sdm-logit "$pfx Starting"
    #
    # If xdm installed, configure it as requested. This is just an example of something that needs to be done
    # after the Phase 1 installs have completed
    #
    if [ -d /etc/X11/xdm ]
    then
	#
	# Configure xdm to allow XDMCP (so VNC works correctly). Enable or disable xdm on the console as requested
	#
	echo "* Editing xdm config files"
	/usr/local/sdm/sdm-logit "$pfx Editing xdm config files" 
	
	sed -i "s/DisplayManager.requestPort:	0/\!DisplayManager.requestPort:	0/" /etc/X11/xdm/xdm-config
	sed -i "s/\#\*					#any host can get a login window/\*					#any host can get a login window/"  /etc/X11/xdm/Xaccess
	# VV This overrides default LISTEN * and disables xdmcp finder (if use 127.0.0.1. OK with 0.0.0.0)
	echo "LISTEN 0.0.0.0" >> /etc/X11/xdm/Xaccess
	if [[ "$poptions" =~ "xdmconsole" ]]
	then
	    sed -i "s/#\:0 local \/usr\/bin\/X :0 vt7 -nolisten tcp/\\:0 local \/usr\/bin\/X :0 vt7 -nolisten tcp/"  /etc/X11/xdm/Xservers
	    echo "Enabling xdm on console"
	    /usr/local/sdm/sdm-logit "$pfx Enabling xdm on console"
	else
	    sed -i "s/\:0 local \/usr\/bin\/X :0 vt7 -nolisten tcp/\#\:0 local \/usr\/bin\/X :0 vt7 -nolisten tcp/"  /etc/X11/xdm/Xservers
	    echo "Disabling xdm on console"
	    /usr/local/sdm/sdm-logit "$pfx Disabling xdm on console"
	fi
    fi
   echo "* Custom Phase post-install completed"
   /usr/local/sdm/sdm-logit "$pfx Completed"
fi
