#!/bin/bash

# Installs packages for X Windows and tigervnc started via systemd

source /usr/local/sdm/sdm-cparse
/usr/local/sdm/sdm-logit "sdm X Installs Starting" 

yes="-y"

[ $aptconfirm -eq 1 ] && yes=""

echo "Installing minimal required components for X windows"
#
# Lines 1,2) Base components. Must be installed, will pull in additional 
# Line 3)    Display Manager and Window Manager. Generally you need one of each
# Line 4)    VNC. Replace or delete as you wish
# Line 5)    miscellaneous X windows apps. Replace and delete as you wish
#
apt install --no-install-recommends $yes xserver-xorg xserver-xorg-core xserver-common xterm x11-apps \
    xfonts-base xfonts-100dpi xfonts-75dpi xfonts-scalable \
    xdm icewm icewm-themes \
    tigervnc-standalone-server \
    chromium-browser firefox-esr xclip xcolors xcolorsel xcolmix retext 

if [ -d /etc/X11/xdm ]
then
   #
   # Configure xdm to allow XDMCP (so VNC works correctly). Enable or disable xdm on the console as requested
   #
   echo""
   echo "** Editing xdm config files..."
   
   sed -i "s/DisplayManager.requestPort:	0/\!DisplayManager.requestPort:	0/" /etc/X11/xdm/xdm-config
   sed -i "s/\#\*					#any host can get a login window/\*					#any host can get a login window/"  /etc/X11/xdm/Xaccess
   # VV This overrides default LISTEN * and disables xdmcp finder (if use 127.0.0.1. OK with 0.0.0.0)
   echo "LISTEN 0.0.0.0" >> /etc/X11/xdm/Xaccess
   if [[ "$poptions" =~ "xdmconsole" ]]
   then
       sed -i "s/#\:0 local \/usr\/bin\/X :0 vt7 -nolisten tcp/\\:0 local \/usr\/bin\/X :0 vt7 -nolisten tcp/"  /etc/X11/xdm/Xservers
       echo "Enabling xdm on console"
       /usr/local/sdm/sdm-logit "sdm X Installs Enabling xdm on console"
   else
       sed -i "s/\:0 local \/usr\/bin\/X :0 vt7 -nolisten tcp/\#\:0 local \/usr\/bin\/X :0 vt7 -nolisten tcp/"  /etc/X11/xdm/Xservers
       echo "Disabling xdm on console"
       /usr/local/sdm/sdm-logit "sdm X Installs Disabling xdm on console"
   fi
fi

echo "Doing apt autoremove just in case..."
apt autoremove

/usr/local/sdm/sdm-logit "sdm X Installs Completed" 
