#!/bin/bash
#
# This file is sourced by other sdm scripts
#
function readparams() {
    #
    # Restores the global variables from /etc/sdm/cparams
    #
    local rpifun value cf="$SDMPT/etc/sdm/cparams"
    if [ -f $cf ]
    then
	while IFS=":" read rpifun value
	do
	    if [[ ! $rpifun =~ ^\ *# && -n $rpifun ]] # skip comment and malformed lines
            then
		#value="${value%%\#*}"    # Del EOL comments
		value="${value%"${value##*[^[:blank:]]}"}"  # Del trailing spaces/tabs
		value="${value#\"}"     # Del opening double-quotes 
		value="${value%\"}"     # Del closing double-quotes 
		value="${value#\'}"     # Del opening single-quotes 
		value="${value%\'}"     # Del closing single-quotes 
		printf -v "$rpifun" "%s" "$value"     #eval "${rpifun}=\"$value\""

	    fi
	done < $cf
    fi
    [ -f $SDMPT/$sdmdir/sdm-cparse ] && source $SDMPT/$sdmdir/sdm-cparse || echo "? Internal error: File '$SDMPT/$sdmdir/sdm-cparse' not found in readparams"
    return
}
# Call the function after we've been sourced
readparams
