#!/bin/bash
#
# This is an sdm plugin for: apps
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
vldargs="|apps|name|"
rqdargs="|apps|"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #
    # Print the keys found (example usage). plugin_getargs returns the list of found keys in $foundkeys
    #
    plugin_printkeys

    if [[ -f $SDMPT/etc/sdm/assets/apps-default ]] && [[ "$name" == "" ]]
    then
	logtoboth "? Plugin $pfx: Default apps list already set; subsequent plugins must provide 'name' argument"
    else
	[ "$name" == "" ] && name="default"
        appfile=$(findappfile "$apps")
        exitiferr "$appfile"
	apps=$(getapplist "$appfile")
	echo "$apps" > $SDMPT/etc/sdm/assets/apps-${name}
        logtoboth "> Plugin $pfx [$name]: Saved apps list: $apps"
    fi

    logtoboth "* Plugin $pfx: Complete Phase 0"

elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    [ "$name" == "" ] && name="default"
    logfreespace "at start of [$name] Application Installs"
    read svapps < /etc/sdm/assets/apps-$name
    if [[ "$virtmode" == "chroot" ]] && [[ "$svapps" =~ "qemu-user-static" ]]
    then
        svapps=${svapps/qemu-user-static}
        deferqemu
    fi
    doinstalls "$svapps" "[$name] Application Installs"

    logfreespace "at end of $pfx [$name] Phase 1"
    logtoboth "* Plugin $pfx: Complete Phase 1"
else
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    #plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #logfreespace "at start of Plugin $pfx Phase post-install"
    #
    #logfreespace "at end of $pfx Custom Phase post-install"
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
