#!/bin/bash
#
# This is an sdm plugin for: apt-config
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
vldargs="|no-install-recommends|confold|confdef|nopager|nocolor|"   #"|list|of|valid|args|"
rqdargs=""                   # |list|of|required|args|or|nullstring|
assetdir="$SDMPT/etc/sdm/assets/$pfx"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs" || exit
    plugin_printkeys
    mkdir -p $assetdir
    logtoboth "* Plugin $pfx: Complete Phase 0"
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #logfreespace "at start of Plugin $pfx Phase 1"
    #
    #
    # Configure requested apt settings
    #
    if [ -v no__install__recommends ]
    then
	logtoboth "> Disable apt install recommends in /etc/apt/apt.conf.d"
	echo "APT::Install-Recommends \"false\";" >> /etc/apt/apt.conf.d/90-sdm-norecommends
    fi
    rm -f /etc/apt/apt.conf.d/10-sdm-force
    if [ -v confold ]
    then
	logtoboth "> Enable apt force-confold in /etc/apt/apt.conf.d"
	echo 'Dpkg::Options "--force-confold";' >> /etc/apt/apt.conf.d/90-sdm-force
    fi
    if [ -v confdef ]
    then
	logtoboth "> Enable apt force-confdef in /etc/apt/apt.conf.d"
	echo 'Dpkg::Options "--force-confdef";' >> /etc/apt/apt.conf.d/90-sdm-force
    fi

    if [ -v nopager ]
    then
	logtoboth "> Disable apt pager in /etc/apt/apt.conf.d"
	echo 'Binary::apt::Pager "false";' >> /etc/apt/apt.conf.d/90-sdm-nopager
    fi
    if [ -v nocolor ]
    then
	logtoboth "> Disable apt color output in /etc/apt/apt.conf.d"
	echo 'Binary::apt::APT::Color "false";' >> /etc/apt/apt.conf.d/90-sdm-nocolor
    fi
    #
    #logfreespace "at end of $pfx Phase 1"
    logtoboth "* Plugin $pfx: Complete Phase 1"
elif [ "$phase" == "post-install" ]
then
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #logfreespace "at start of Plugin $pfx Phase post-install"
    #

    #
    #logfreespace "at end of $pfx Custom Phase post-install"
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
