#!/bin/bash
#
# This is an sdm plugin for: apt-cacher-ng
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    local mpt=""
    [ "$SDMNSPAWN" == "Phase0" ] && mpt=$SDMPT
    source $mpt/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1:arg2=val2:arg3=val3: ...

#
# Main code for the script
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    loadparams
    logtoboth "* Plugin $pfx: Start Phase 0"

# INSERT Plugin Phase 0 code here
    
    logtoboth "* Plugin $pfx: Complete Phase 0"

elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    loadparams
    logtoboth "* Plugin $pfx: Start Phase 1"
    #logfreespace "at start of Plugin $pfx Phase 1"
    #
    # INSERT your Plugin Phase 1 customization stuff here
    # In Phase 1 all references to directories in the image can be direct
    #
    #logfreespace "at end of $pfx Phase 1"
    logtoboth "* Plugin $pfx: Complete Phase 1"
else
    #
    # Plugin Post-install edits
    #
    loadparams
    logtoboth "* Plugin $pfx: Start Phase post-install"
    #logfreespace "at start of Plugin $pfx Phase post-install"
    #
    plugin_getargs $pfx "$args" "|gentargetmode|bindaddress|cachedir|port|tunnelenable|proxy|"
    plugin_printkeys

    #  Possible choices FOR gentargetmode: Set up once, Set up now and update later, No automated setup
    #  Other settings: "keep" keeps the value from the default install

    [ "$gentargetmode" == "" ] && gentargetmode="No automated setup"
    [ "$bindaddress" == "" ] && bindaddress="keep"
    [ "$cachedir" == "" ] && cachedir="keep"
    [ "$port" == "" ] && port="keep"
    [ "$tunnelenable" == "" ] && tunnelenable="false"
    [ "$proxy" == "" ] && proxy="keep"
    debconf-set-selections <<< "apt-cacher-ng apt-cacher-ng/gentargetmode string $gentargetmode"
    debconf-set-selections <<< "apt-cacher-ng apt-cacher-ng/bindaddress string bindaddress"
    debconf-set-selections <<< "apt-cacher-ng apt-cacher-ng/cachedir string $cachedir"
    debconf-set-selections <<< "apt-cacher-ng apt-cacher-ng/port string $port"
    debconf-set-selections <<< "apt-cacher-ng apt-cacher-ng/tunnelenable string $tunnelenable"
    debconf-set-selections <<< "apt-cacher-ng apt-cacher-ng/proxy string $proxy"

    logtoboth "> Plugin $pfx: Install apt-cacher-ng server and set caching server to 127.0.0.1"
    logtoboth "> Plugin $pfx:   With arguments:"
    logtoboth "> Plugin $pfx:                gentargetmode: $gentargetmode"
    logtoboth "> Plugin $pfx:                bindaddress:   $bindaddress"
    logtoboth "> Plugin $pfx:                cachedir:      $cachedir"
    logtoboth "> Plugin $pfx:                port:          $port"
    logtoboth "> Plugin $pfx:                tunnelenable:  $tunnelenable"
    logtoboth "> Plugin $pfx:                proxy:         $proxy"
    doapt "install --no-install-recommends -y apt-cacher-ng" $showapt

    logtoboth "> Plugin $pfx: Set apt-cacher-ng to enable after First Boot"
    acs01="/etc/sdm/0piboot/099-enable-apt-cacher-ng.sh"
    cat > $acs01 <<EOF
#!/bin/bash
rm -f /etc/apt/apt.conf.d/02proxy
echo "Acquire::http::proxy \"http://127.0.0.1:3142\";" >> /etc/apt/apt.conf.d/02proxy
systemctl enable apt-cacher-ng > /dev/null 2>&1
EOF
    chmod 755 $acs01

    #logfreespace "at end of $pfx Custom Phase post-install"
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
