#!/bin/bash
#
# This is an sdm plugin for: bootconfig
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
vldargs=""
rqdargs=""
assetdir="$SDMPT/etc/sdm/assets/bootconfig"


if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #
    # Print the keys found (example usage). plugin_getargs returns the list of found keys in $foundkeys
    #
    plugin_printkeys
    if [ "$foundkeys" != "" ]
    then
	logtoboth "> Plugin $pfx: Processing keys..."

	# special processing for certain keys
	[ -v inline ] && inline="1"
	[ -v hdmi_ignore_edid -a "$hdmi_ignore_edid" == "" ] && hdmi_ignore_edid="0xa5000080"

	IFS="|" read -a fargs <<< "$foundkeys"
	for c in "${fargs[@]}"
	do
	    value="${!c}"
	    case "$c" in
		comment)
		    logtoboth "> Plugin $pfx: Add comment to $SDMPT/boot/config.txt: $value"
		    #[ "$value" != "${value#\\n}" ] && value="\n#${value#\\n}" || value="#${value}"
		    printf "$value\n" >> $SDMPT/boot/config.txt
		    ;;
		#inline)
		    #inline="1"  # Already set above of course
		    #;;
		reset)
		    if [ "$reset" != "" ]
		    then
			if [ -f $reset ]
			then
			    logtoboth "% Plugin $pfx: Reset /boot/config.txt with '$reset'"
			    [ ! -f $SDMPT/boot/config.txt.sdm ] && mv $SDMPT/boot/config.txt $SDMPT/boot/config.txt.sdm
			    rm -f $SDMPT/boot/config.txt
			    cp -a $reset $SDMPT/boot/config.txt
			    setfileownmode $SDMPT/boot/config.txt 755
			else
			    logtoboth "? Plugin $pfx: /boot/config.txt reset file '$reset' not found"
			fi
		    else
			logtoboth "% Plugin $pfx: Reset /boot/config.txt to null file"
			[ ! -f $SDMPT/boot/config.txt.sdm ] && mv $SDMPT/boot/config.txt $SDMPT/boot/config.txt.sdm
			rm -f $SDMPT/boot/config.txt
			touch $SDMPT/boot/config.txt
		    fi
		    ;;
		*)
		    [ "$c" != "inline" ] && updateconfigtxt "$c" "$value" "Plugin $pfx: " "$inline"
		;;
	    esac
	done
    fi
    logtoboth "* Plugin $pfx: Complete Phase 0"

elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #logfreespace "at start of Plugin $pfx Phase 1"
    #
    #logfreespace "at end of $pfx Phase 1"
    logtoboth "* Plugin $pfx: Complete Phase 1"
else
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #logfreespace "at start of Plugin $pfx Phase post-install"
    #
    #logfreespace "at end of $pfx Custom Phase post-install"
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
