#!/bin/bash
#
# This is an sdm plugin for: btwifiset
#
# btwifiset is the back-end service for the iOS app BTBerryWiFi
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
vldargs="|country|localsrc|btwifidir|timeout|logfile|"
loadparams

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$args" "$vldargs" "|country|"
    #
    # Print the keys found (example usage). plugin_getargs returns the list of found keys in $foundkeys
    #
    plugin_printkeys
    #plugin_dbgprint "This is how to do a Plugin Debug printout"      # Will only be printed if --plugin-debug specified
    #
    # Copy the btwifiset files
    #
    [ "$btwifidir" == "" ] && btwifidir="/usr/local/btwifiset"
    srcurl="https://raw.githubusercontent.com/nksan/Rpi-SetWiFi-viaBluetooth/main"
    mkdir -p $SDMPT/$btwifidir
    if [ "$localsrc" != "" ]
    then
	#
	# Copy the btwifiset files from local stash
	#
	logtoboth "> Plugin $pfx: Copy btwifiset from $localsrc to $btwifidir"
	for f in btwifiset.py
	do
	    cp $localsrc/$f $SDMPT/$btwifidir/$f
	done
    else
	logtoboth "> Plugin $pfx: Download btwifiset from the internet to $btwifidir"
	for f in btwifiset.py
	do
	    wget $srcurl/$f --output-document=$SDMPT/$btwifidir/$f
	    wsts=$?   # Need to fix this if more files ever added
	done
	if [ ! $wsts ]
	then
	    logtoboth "?!Plugin $pfx: Unable to download btwifiset from $srcurl (Error $wsts)"
	    logtoboth "  btwifiset cannot be installed"
	fi
    fi
    logtoboth "* Plugin $pfx: Complete Phase 0"

elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs" "|country|"
    #logfreespace "at start of Plugin $pfx Phase 1"

    logtoboth "> Plugin $pfx: Install required Python components"
    # V Assumes Python versions in the form of nn.nn.nn (which they all seem to be)
    pyver=$((python3 --version) | (read p version junk ; echo ${version%.*}))
    doaptrpterror "install python3-gi libdbus-glib-1-dev python3-pip libpython${pyver}-dev --yes" $showapt 
    logtoboth "> Plugin $pfx: Install Python dbus module using python pip"
    cat >> /etc/sdm/apt.log <<EOF

$(thisdate) pip install dbus-python

EOF
    pip install dbus-python >> /etc/sdm/apt.log 2>&1
    [ ! $? ] && logtoboth "% Plugin $pfx: Error returned from 'pip install dbus-python'; Review /etc/sdm/apt.log"

    #logfreespace "at end of $pfx Phase 1"
    logtoboth "* Plugin $pfx: Complete Phase 1"
else
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$args" "$vldargs" "|country|"
    #logfreespace "at start of Plugin $pfx Phase post-install"
    [ "$btwifidir" == "" ] && btwifidir="/usr/local/btwifiset"

    # Handle wpa_supplicant.conf
    found=0
    for wpa in /etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
    do
	if [ -f $wpa ]
	then
	    found=1
	    if ! grep "country=$country" $wpa > /dev/null 2>&1
	    then
		logtoboth "> Plugin $pfx: Add 'country=$country' to $wpa"
		sed -i "1 a country=$country" $wpa
	    fi
	    if ! grep "update_config=1" $wpa > /dev/null 2>&1
	    then
		logtoboth "> Plugin $pfx: Add 'update=1' to $wpa"
		sed -i "1 a update_config=1" $wpa
	    fi
	fi
    done
    if [ $found -eq 0 ]
    then
	logtoboth "> Plugin $pfx: No wpa_supplicant.conf found; Creating..."
	cat > /etc/wpa_supplicant/wpa_supplicant.conf <<EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
country=$country
update_config=1
EOF
    fi
    # Modify bluetooth service
    logtoboth "> Plugin $pfx: Update ExecStart for bluetooth service as needed"
    if ! sed -n '/^ExecStart/p' /lib/systemd/system/bluetooth.service | grep -q '\-\-experimental'
    then
	# Append --experimental to end of command line
	sed 's/^ExecStart.*bluetoothd\b/& --experimental/' /lib/systemd/system/bluetooth.service > /etc/systemd/system/bluetooth.service
    else
	cp /lib/systemd/system/bluetooth.service /etc/systemd/system
    fi
    if ! sed -n '/ExecStart/p' /etc/systemd/system/bluetooth.service | grep -q '\-P battery'
    then
	# Append -P battery to end of command line
	sed -i 's/^ExecStart.*experimental\b/& -P battery/' /etc/systemd/system/bluetooth.service
    fi

    # Undo sdm disable wifi and bluetooth if done

    [ -f /etc/sdm/0piboot/050-disable-bt.sh ]   && mv /etc/sdm/0piboot/050-disable-bt.sh /etc/sdm/0piboot/.050-disable-bt.sh-btwifiset
    [ -f /etc/sdm/0piboot/055-disable-wifi.sh ] && mv /etc/sdm/0piboot/055-disable-wifi.sh /etc/sdm/0piboot/.055-disable-wifi.sh-btwifiset

    # Enable hciuart service
    systemctl enable hciuart > /dev/null 2>&1

    # Create btwifiset service
    logtoboth "> Plugin $pfx: Create btwifiset service"
    [ "$timeout" != "" ] && switches="--timeout $timeout" || switches=""
    [ "$logfile" != "" ] && switches="$switches --logfile $logfile" || switches="$switches --syslog"
    cat >> /etc/systemd/system/btwifiset.service <<EOF
[Unit]
Description=btwifi Configure Wi-Fi over Bluetooth
After=hciuart.service bluetooth.target

[Service]
Type=simple
ExecStart=/bin/python3 $btwifidir/btwifiset.py $switches

[Install]
WantedBy=multi-user.target
EOF
    #
    # Link bluetooth.target.wants to the correct copy of bluetooth.service
    #
    systemctl enable btwifiset.service
    if [ -f /etc/systemd/system/bluetooth.target.wants/bluetooth.service ]
    then
	rm -f /etc/systemd/system/bluetooth.target.wants/bluetooth.service
	ln -s /etc/systemd/system/bluetooth.service /etc/systemd/system/bluetooth.target.wants/bluetooth.service
    fi
    if [ -f /etc/systemd/system/dbus-org.bluez.service ]
    then
	rm -f /etc/systemd/system/dbus-org.bluez.service
	ln -s /etc/systemd/system/bluetooth.service /etc/systemd/system/dbus-org.bluez.service
    fi

    #logfreespace "at end of $pfx Custom Phase post-install"
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
