#!/bin/bash
#
# This is an sdm plugin for: chrony
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
vldargs="|conf|conf2|conf3|source|source2|source3|"
rqdargs=""

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$args" "$vldargs"
    #
    # Print the keys found (example usage). plugin_getargs returns the list of found keys in $foundkeys
    #
    plugin_printkeys
    #
    # Copy files into the IMG
    #
    for id in conf conf2 conf3 source source2 source3
    do
	idf="${!id}"
	if [ "$idf" != "" ]
	then
	    idfn="$(basename $idf)"
	    [[ "$id" =~ "conf" ]] && idfext=".conf" || idfext=".source"
	    logtoboth "> Plugin $pfx: Copy '$id' config file '$idf' to /etc/sdm/assets"
	    dstfn=$(basename ${idf%%$idfext}$idfext)
	    cp -a $idf $SDMPT/etc/sdm/assets/chronyd-$id-$dstfn
	fi
    done
    logtoboth "* Plugin $pfx: Complete Phase 0"

elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs"
    doaptrpterror "install --no-install-recommends --yes chrony" $showapt
    logtoboth "* Plugin $pfx: Complete Phase 1"
else
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$args" "$vldargs"
    for id in conf conf2 conf3 source source2 source3
    do
	for fn in /etc/sdm/assets/chronyd-$id-*
	do
	    [[ "$id" =~ "chronyd-conf-" ]] && dstdir="/etc/chrony/conf.d" || dstdir="/etc/chrony/sources.d"
	    tfn="${fn##*chronyd-$id-}"
	    logtoboth "> Plugin $pfx: Copy chronyd file '$tfn' to $dstdir"
	    cp -a $fn $dstdir/$(basename $tfn)
	done
    done
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
