#!/bin/bash
#
# This is an sdm burn plugin for: cryptpart
#
# The plugin is called once as a burn plugin.
#

function cpcleanup() {
    echo "> Close LUKS partition '$cryptname'"
    cryptsetup luksClose $cryptname
}

function cpoptions() {
    local sts=$1

    echo "% cryptsetup returned an error ($sts)"
    echo "% If you mis-typed 'YES' or want to try again enter Y or y"
    if ! askyn "Retry"
    then
	logtobothex "? Plugin $pfx: Exit per user request"
    fi
    return 0
}

function getdevuuid() {
    #
    # Find PARTUUID or UUID for device/partition
    # If device name is specified instead of a partition (/dev/sdc vs /dev/sdc1) blkid returns a PTUUID which is the UUID
    #
    local pname=$1
    local blkidstr=$(blkid $pname) p1 uuid uuidstr=""

    for pt in PARTUUID PTUUID UUID
    do
	p1=${blkidstr##*$pt=\"}
	if [ "$p1" != "$blkidstr" ] # Different if we trimmed off part
	then
	    # Found it!
            uuid="${p1%%\"*}"       # Get to the little L uuid only
	    [ "$pt" == "PTUUID" ] && uuidstr="UUID=$uuid" || uuidstr="$pt=$uuid"
            break
	fi
    done
    echo "$uuidstr"
}

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
vldargs="|burndev|burnfilefile|cryptname|fslabel|fstype|keydisk-id|keyfile|keyfile-location|mountpoint|nbde-server|nocreate|nonint|nopwd|partname|passphrase|"
rqdargs="|cryptname|fstype|partname|"
assetdir="$SDMPT/etc/sdm/assets/$pfx"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs" || exit
    [[ "$SDMNSPAWN" =~ Live ]] || logtobothex "? Plugin $pfx: Plugin invalid except with --runonly plugins on a live system"
    #
    # Print the keys found (example usage). plugin_getargs returns the list of found keys in $foundkeys
    #
    plugin_printkeys
    mkdir -p $assetdir
    [ "$keyfile__location" == "" ] || keyfile__location=${keyfile__location,,}
    [[ "|root|usb|" =~ $keyfile__location ]] || logtobothex "? Plugin $pfx: '$keyfile__location' invalid value for 'keyfile-location'"
    [ "$fstype" != "" ] && [[ "btrfs,ext4" =~ $fstype ]] || logtobothex "? Plugin $pfx: Invalid fstype '$fstype'"
    [ -v mountpoint ] && [ "$fstype" == "" ] && logtobothex "? Plugin $pfx: 'mountpoint' requires 'fstype' argument"
    [ -v nopwd ] && [ "$keyfile" ==  "" ] && logtobothex "? Plugin $pfx: 'nopwd' requires 'keyfile' argument"
    [ -v nonint ] && [ "$keyfile" == "" ] && [ "$passphrase" == "" ] && logtobothex "? Plugin $pfx: 'nonint' requires 'keyfile' or 'passphrase'"
    [ "$(getdevuuid $partname)" == "" ] && logtobothex "? Plugin $pfx: Unable to obtain PARTUUID or UUID for '$partname'; does the device/partition exist?"
    [ "$keyfile__location" == "" ] && keyfile__location=root
    if [ "${keyfile__location,,}" == "usb" ]
    then
	[ "$keydisk__id" == "" ] && logtobothex "keyfile-location=usb requires keydisk-id"
    fi

    if [ "$keyfile" != "" ]
    then
	[ -f $keyfile ] || logtobothex "? Plugin $pfx: Keyfile '$keyfile' not found"
	if [ "$(dirname $keyfile)" != "/root" ] && [ "$keyfile__location" == "root" ]
	then
	    logtoboth "% Plugin $pfx: Copy keyfile '$keyfile' to /root"
	    cp $keyfile /root
	fi
	chmod 400 /root/$(basename $keyfile)
    fi

    # Don't allow nbde and usb keydisk. Trying to sync 2 asynchronous systemd services is darn near impossible
    [[ "$nbde__server" != "" ]] && [[ "${keyfile__location,,}" == "usb" ]] && logtobothex "? Plugin $pfx: NBDE server with USB keyfile not supported; use 'keyfile-location=root'"
    # Partition must be empty and not mounted
    if grep -q -s $partname /proc/mounts
    then
	logtoboth   "? Plugin $pfx: Partition '$partname' must not be mounted"
	logtoboth   "? Plugin $pfx: If partition '$partname' contains data you wish to keep"
	logtobothex "? Plugin $pfx: You must save it before running cryptpart and restore it afterwards"
    fi

    logtoboth "* Plugin $pfx: Complete Phase 0"
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #logfreespace "at start of Plugin $pfx Phase 1"

    pkgs="systemd-cryptsetup"
    [ "$nbde__server" != "" ] && pkgs="clevis clevis-initramfs $pkgs"
    [ "$(type -p cryptsetup)" == "" ] && pkgs="cryptsetup cryptsetup-initramfs cryptsetup-bin $pkgs"
    logtoboth "> Plugin $pfx: Install $pkgs"
    installpkgsif "$pkgs"

    if grep -q -s luks.crypttab=no /boot/firmware/cmdline.txt
    then
	logtoboth "> Remove 'luks.crypttab=no' from cmdline.txt to enable systemd-cryptsetup-generator"
	sed -i "s/luks.crypttab=no//g" /boot/firmware/cmdline.txt
    fi

    #logfreespace "at end of $pfx Phase 1"
    logtoboth "* Plugin $pfx: Complete Phase 1"

elif [ "$phase" == "post-install" ]
then
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs" || exit
    plugin_printkeys

    # Partition must be empty and not mounted
    grep -q -s $partname /proc/mounts && logtobothex "? Partition '$partname' must not be mounted"

    if [ "$keyfile" != "" ]
    then
	[ "$keyfile__location" == "" ] && keyfile__location=root || keyfile__location=${keyfile__location,,}
    else
	keyfile__location=""
    fi

    # encrypt the partition
    [ "$cipher" == "" ] && cipher="aes-xts-plain64"
    trap "cpcleanup" EXIT
    if [ "$keyfile" != "" ]
    then
	kfn=$(basename $keyfile)
	kf=/root/$kfn
    fi
    if [ ! -v nocreate ]
    then
	if [ -v nopwd ]
	then
	    logtoboth "> Plugin $pfx: Enable LUKS encryption on partition '$partname' using keyfile '$kfn'"
	    if [ -v nonint ]
	    then
		printf "YES\n" | cryptsetup luksFormat --type luks2 $partname $kf || logtobthex "? Plugin $pfx: cryptsetup luksFormat failed ($?)"
	    else
		while [ 0 ]
		do
		    cryptsetup luksFormat --type luks2 $partname $kf
		    sts=$?
		[ $sts -eq 0 ] && break
		cpoptions $sts || logtobothex "? Plugin $pfx: Exit per user request"
		done
	    fi
	else
	    logtoboth "> Plugin $pfx: Enable LUKS encryption on partition '$partname' with a passphrase"
	    if [ -v nonint ]
	    then
		printf "$passphrase\n$passphrase\nYES\n" | cryptsetup luksFormat --type luks2 --cipher $cipher --hash sha256 --iter-time 5000 --key-size 256 --pbkdf argon2i $partname || logtobothex "? Plugin $pfx: cryptsetup luksFormat failed ($?)"
	    else
		while [ 0 ]
		do
		    cryptsetup luksFormat --type luks2 --cipher $cipher --hash sha256 --iter-time 5000 --key-size 256 --pbkdf argon2i $partname
		    sts=$?
		    [ $sts -eq 0 ] && break
		    cpoptions $sts || logtobothex "? Plugin $pfx: Exit per user request"
		done
	    fi
	    if [ "$keyfile" != "" ]
	    then
		logtoboth "> Plugin $pfx: Add keyfile '$kfn' to Luks partition '$partname'"
		printf "$passphrase\n" | cryptsetup luksAddKey $partname $kf || logtobothex "? Plugin $pfx: cryptsetup luksAddKey failed ($?)"
	    fi
	fi
	if [ "$nbde__server" != "" ]
	then
	    logtoboth "> Plugin $pfx: Configure Network Bound Disk Encryption (NBDE)"
	    logtoboth "> Plugin $pfx: Create and enable NBDE unlock service clevis-unlock-$cryptname"
            if [ "$keyfile" == "" ]
            then
                logtoboth "> Plugin $pfx: Enable NBDE using passphrase with server $nbde__server"
                printf "$passphrase\n" | clevis luks bind -f -y -d $partname tang "{\"url\":\"$nbde__server\"}"
            else
                logtoboth "> Plugin $pfx: Enable NBDE using keyfile with server $nbde__server"
                #logtoboth "DD kf:|$kf| partname:|$partname| nbde-server:|$nbde__server|"
                clevis luks bind -f -y -k $kf -d $partname tang "{\"url\":\"$nbde__server\"}"
            fi

            uuidstr=$(getdevuuid $partname)
            uuidstr=${uuidstr#*=}
	    [ "$keyfile" == "" ] && dowall="wall"
	    cat > /etc/systemd/system/clevis-unlock-$cryptname.service <<EOF
[Unit]
Description=sdm Unlock data volume $cryptname
DefaultDependencies=no
After=systemd-udevd.service systemd-udev-settle.service
After=local-fs.target
Before=getty.target multi-user.target
Wants=network-online.target

[Service]
Type=forking
#sdm-clevis-unlock arguments: partuuid cryptname mountpoint retries [D:12] sleepsec [D:5] wall
ExecStart=/usr/local/bin/sdm-clevis-unlock /dev/disk/by-partuuid/$uuidstr "$cryptname" "$mountpoint" 12 5 $dowall
TimeoutSec=0
RemainAfterExit=yes
GuessMainPID=no

[Install]
WantedBy=multi-user.target
EOF
	    [ -f /usr/local/bin/sdm-clevis-unlock ] || cat > /usr/local/bin/sdm-clevis-unlock <<'EOF'
#!/bin/bash

if [ "$1" != "fork" ]
then
    $0 fork $* &
    exit
fi
devpartuuid="$2"
cryptname="$3"
mountpoint="$4"
retries="${5:-12}"
sleepsec="${6:-5}"
dowall="$7"

mapper="/dev/mapper/$cryptname"
#echo "Start: cryptname:|$cryptname| mountpoint:|$mountpoint| devpartuuid:|$devpartuuid|"

[ -e $mapper ] && { echo "$mapper is already unlocked" ; exit 0 ; }

echo "Trying Clevis unlock for $retries times sleeping $sleepsec seconds"
retimes=1
while [ $retimes -le $retries ]
do
    if clevis luks unlock -d $devpartuuid -n $cryptname || [ -e $mapper ]
    then
        echo "Clevis unlock successful"
        break
    fi
    echo "Clevis unlock failed; Sleep $sleepsec seconds; retry ${retimes}/${retries}..."
    sleep $sleepsec
    retimes=$((retimes+1))
done

if [ ! -e $mapper ]
then
    echo "Clevis unlock failed; trying keyfile/passphrase via systemd-cryptsetup@$cryptname.service"
    [ "$dowall" == "wall" ] && wall -t 10 "Use 'systemd-tty-ask-password-agent --query' to unlock '$cryptname'"
    systemctl start systemd-cryptsetup@$cryptname.service
fi

[ -e $mapper ] || { echo "Unlock $cryptname failed" ; exit 1 ; }
[ "$mountpoint" == "" ] && { echo "No mountpoint configured for $mapper. Done." ; exit 0 ; }

echo "Mount $mountpoint"
mount $mountpoint
sts=$?
[ $sts -eq 0 ] && { echo "Done" ; exit 0 ; } || { echo "Mount failed" ; exit $sts ; }
EOF
	    chmod 755 /usr/local/bin/sdm-clevis-unlock
	    systemctl enable clevis-unlock-$cryptname.service
	fi
    fi
    if [ -v nopwd ]
    then
	logtoboth "> Plugin $pfx: Open encrypted partition '$partname' with keyfile '$kfn'"
	cryptsetup luksOpen $partname $cryptname --key-file $kf || logtobothex "? Plugin $pfx: Error opening encrypted partition '$partname' ($?)"
    else
	logtoboth "> Plugin $pfx: Open encrypted partition '$partname' with passphrase"
	printf "$passphrase\n" | cryptsetup luksOpen $partname $cryptname || logtobothex "? Plugin $pfx: Error opening encrypted partition '$partname' ($?)"
    fi
    if [ ! -v nocreate ]
    then
	# make file system
	[ "$fslabel" != "" ] && mklabel="-l $fslabel"
	[ "$fstype" == "" ] && fstype=ext4
	case "$fstype" in
	    btrfs|ext4)
		if [ "$fstype" == "btrfs" ] && [ "$(type -p mkfs.btrfs)" == "" ]
		then
		    logtoboth "> Plugin $pfx: Install btrfs-progs"
		    installpkgsif btrfs-progs
		fi
		logtoboth "> Plugin $pfx: Create '$fstype' file system on the encrypted partition"
		mkfs.$fstype -q $mklabel /dev/mapper/$cryptname || logtobothex "? Plugin $pfx: mkfs.$fstype failed ($?)"
		;;
	    *)
		logtobothex "? Plugin $pfx: Unrecognized fstype '$fstype'"
		;;
	esac
    fi
    # add to /etc/crypttab and fstab

    logtoboth "> Plugin $pfx: Update config files..."

    kfloc="none" ; opts=""
    if [ "$nbde__server" != "" ]
    then
	opts=",noauto"
    fi
    if [ "$keyfile" != "" ]
    then
        opts="${opts},tries=3"
	[ "$keyfile__location" == "root" ] && kfloc="/root/$kfn"
        if [ "$keyfile__location" == "usb" ]
	then
	    mountname=${partname#/dev/}
	    dirname="${mountname}Key"
	    mountsvc="tmp-$dirname"
	    # create mount point
	    mkdir -p /tmp/$dirname
	    logtoboth "> Plugin $pfx: Create systemd mount unit to automount the USB disk"
	    # create systemd mount unit to mount the USB disk so the keyfile is available
	    cat > /etc/systemd/system/$mountsvc.mount <<EOF
[Unit]
Description=USB key to LUKS unlock partition $partname
DefaultDependencies=no
Before=cryptsetup.target

[Mount]
What=$keydisk__id
Where=/tmp/$dirname
Options=ro

[Install]
WantedBy=cryptsetup.target
EOF
	    # create systemd service to dismount the disk after systemd-cryptsetup
	    cat > /etc/systemd/system/$dirname-unmount.service <<EOF
[Unit]
Description=Service umount USB key after LUKS unlock partition $partname
After=systemd-cryptsetup@$cryptname.service
Requires=systemd-cryptsetup@$cryptname.service

[Service]
Type=oneshot
ExecStart=/usr/bin/umount /tmp/$dirname

[Install]
WantedBy=systemd-cryptsetup@$cryptname.service
EOF
	    kfloc="/tmp/$dirname/$kfn"
	    opts="${opts},nofail,x-systemd.device-timeout=0"
	fi
    fi
    logtoboth "> Plugin $pfx: Update /etc/crypttab"
    # Use UUID rather than partname in crypttab
    uuidstr=$(getdevuuid $partname)
    [ "$uuidstr" == "" ] && logtobothex "? Plugin $pfx: Unable to obtain PARTUUID or UUID for '$partname'; does the device/partition exist?"
    [ "$mountpoint" != "" ] && echo "# This V device mounted in /etc/fstab" >> $SDMPT/etc/crypttab
    echo "$cryptname	$uuidstr $kfloc luks,discard${opts}" >> $SDMPT/etc/crypttab
    
    # add to fstab
    if [ "$mountpoint" != "" ]
    then
	logtoboth "> Plugin $pfx: Create mountpoint '$mountpoint'"
	mkdir -p $mountpoint
	logtoboth "> Plugin $pfx: Update fstab"
	opts="defaults,nofail"
	[ "$nbde__server" != "" ] && opts="${opts},noauto"
	echo "# Device '/dev/mapper/$cryptname' defined in /etc/crypttab" >> $SDMPT/etc/fstab
	echo "/dev/mapper/$cryptname  $mountpoint  $fstype $opts  0  2" >> $SDMPT/etc/fstab
    else
	logtoboth "> Plugin $pfx: Skip fstab update; no mountpoint specified"
    fi
    if [ "$keyfile__location" == "usb" ]
    then
	logtoboth "> Plugin $pfx: Ensure that you have a LUKS USB keydisk prepared before restarting the system"
	logtoboth "> Plugin $pfx: Ignore any non-existent unit 'systemd-cryptsetup@$cryptname.service' message"
	systemctl daemon-reload
	systemctl enable $mountsvc.mount $dirname-unmount.service
    fi
    logtoboth "> Plugin $pfx: Reboot the system when ready"
fi

exit


