#!/bin/bash
#
# This is an sdm plugin for: defer-plugin
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function do_add_deferred_action() {
    local dline="$1"

    if [[ "$dline" =~ ^defer-reboot ]] || [[ "$dline" =~ ^defer-command ]]
    then
	logtoboth "> Plugin $pfx: Configure post-defer service '$dline'"
	echo "$dline" >> $assetdir/defer-done-options
    else
	logtoboth "> Plugin $pfx: Add deferred pluglist item '$dline'"
	add_defer_plugin "$dline"
    fi
}

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
assetdir="$SDMPT/etc/sdm/assets/$pfx"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"

    if [ "${args:0:1}" == "@" ]
    then
	args=${args:1:999}
	# process the plugfile
	[ -f $args ] || logtobothex "? Plugin $pfx: Pluglist file '$args' not found"
	while read line
	do
	    do_add_deferred_action "$line"
	done < $args
    else
	do_add_deferred_action "$args"
    fi
    logtoboth "* Plugin $pfx: Complete Phase 0"
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    logtoboth "* Plugin $pfx: Complete Phase 1"
elif [ "$phase" == "post-install" ]
then
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
exit
