#!/bin/bash
#
# This is an sdm plugin for: ln
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

function converty() {
    [ -v force ] && force=y
    [ -v symbolic ] && symbolic=y
    [ -v hard ] && hard=y
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
vldargs="|target|linkname|force|symbolic|"
rqdargs="|target|linkname|"                   # |list|of|required|args|or|nullstring|
assetdir="$SDMPT/etc/sdm/assets/$pfx"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    #logtoboth "* Plugin $pfx: Start Phase 0"
    #plugin_getargs $pfx "$args" "$vldargs" "$rqdargs" || exit
    #plugin_printkeys
    logtoboth "* Plugin $pfx: Complete Phase 0"
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    #logtoboth "* Plugin $pfx: Start Phase 1"
    #plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    logtoboth "* Plugin $pfx: Complete Phase 1"
elif [ "$phase" == "post-install" ]
then
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    converty
    [ "$force" == "y" ] && fx="--force"
    fln="link"
    [ "$symbolic" == "y" ] && fsym="--symbolic" && fln="symbolic link"
    logtoboth "> Plugin $pfx: Add $fln '$linkname' target '$target'"
    ln $fx $fsym $target $linkname
    sts=$?
    [ $sts -ne 0 ] && logtobothex "? Plugin $pfx: ln command failed ($?)"
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
