#!/bin/bash
#
# This is an sdm plugin for: lxde
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
vldargs="|lhmouse|lxde-config|user|"
rqdargs=""
assetdir="$SDMPT/etc/sdm/assets/lxde"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    plugin_printkeys
    [ "$user" != "" ] && username=$user || username="default"
    if [ "$lxde__config" != "" ]
    then
	IFS="," read -a largs <<< "$lxde__config"
	for lx in "${largs[@]}"
	do
	    IFS=":=" read lxname lxfname <<< "$lx"
	    case "${lxname,,}" in
		libfm|pcmanfm|lxterminal)
		    mkdir -p $assetdir/$lxname/$username
		    if [ -f $lxfname ]
		    then
			logtoboth "> Plugin $pfx: Copy '$lxfname' to $assetdir/$lxname/$username"
			cp -a $lxfname $assetdir/$lxname/$username
		    else
			logtoboth "? Plugin $pfx: lxde-config type '$lxname' file '$lxfname' not found"
		    fi
		    ;;
		*) logtoboth "% Plugin $pfx: lxde-config item '$lxname' is unknown"
		   ;;
	    esac
	done
    fi
    logtoboth "* Plugin $pfx: Complete Phase 0"

elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #logfreespace "at start of Plugin $pfx Phase 1"
    #
    # INSERT your Plugin Phase 1 customization stuff here
    # In Phase 1 all references to directories in the image can be direct
    #
    #logfreespace "at end of $pfx Phase 1"
    logtoboth "* Plugin $pfx: Complete Phase 1"
else
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    [ "$user" != "" ] && srcuser=$user || srcuser="default"
    dstuser=$user
    [ "$dstuser" == "" ] && dstuser=$myuser
    if [ "$dstuser" == "" ]
    then
	logtoboth "% Plugin $pfx: No users created with user plugin"
	exit
    fi
    #logfreespace "at start of Plugin $pfx Phase post-install"

    if [ -f /usr/bin/startlxde-pi ]
    then
	logtoboth "> Plugin $pfx: Special LXDE-Pi handling"
	gx=$(stat -c '%G' /home/$dstuser)
	[ "$gx" == "" ] && gx=users
	mkdir -p /home/$dstuser/.config
	if [ -d /etc/wayfire ]
	then
	    cp /etc/wayfire/template.ini /home/$dstuser/.config/wayfire.ini
	    setfileownmmode /home/$dstuser/.config/wayfire.ini 644 $dstuser:$gx
	    [ "$keymap" != "" ] && sed -i "s/xkb_layout.*=.*/xkb_layout=$keymap/" /home/$dstuser/.config/wayfire.ini
	fi
	# Set left-handed mouse if requested
	if [ -v lhmouse ]
	then
	    logtoboth "> Plugin $pfx: Enable left-handed mouse for user '$dstuser'"
	    if [ -f /home/$dstuser/.config/wayfire.ini ]
	    then
		sed -i '/xkb_layout.*=.*/a left_handed_mode=true' /home/$dstuser/.config/wayfire.ini
	    fi
	    dirx="/home/$dstuser/.config/lxsession/LXDE-pi"
	    mkdir -p $dirx
	    cp -a /etc/xdg/lxsession/LXDE-pi/desktop.conf $dirx
	    setfileownmode $dirx/desktop.conf 644 $dstuser:$gx
	    sed -i "s/LeftHanded=0/LeftHanded=1/" $dirx/desktop.conf
	fi
	# Copy LXDE config files if requested
	if [ "$lxde__config" != "" ]
	then
	    for lx in libfm pcmanfm lxterminal
	    do
		dirx="/home/$dstuser/.config/$lx"
		if compgen -G "$assetdir/$lx/$srcuser/*" > /dev/null
		then
		    logtoboth "> Plugin $pfx: Copy '$lx' config file to $dirx/$lx.conf"
		    mkdir -p $dirx
		    cp -a $assetdir/$lx/$srcuser/* $dirx/$lx.conf
		fi
	    done
	fi
	logtoboth "> Plugin $pfx: Set owner to '$dstuser:$gx' and protection to 700 on '/home/$dstuser/.config' directory tree"
	chown -R $dstuser:$gx /home/$dstuser/.config
	chmod 700 /home/$dstuser/.config
    else
	logtoboth "% Plugin $pfx: LXDE not installed on this system"
    fi

    #logfreespace "at end of $pfx Custom Phase post-install"
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
