#!/bin/bash
#
# This is an sdm plugin for: network
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

function getdefnm() {
    #
    # $1 has user-provided $netman
    #
    local dfn="$1"
    if [ "$dfn" != "" ]
    then
	[ "$dfn" == "nm" ] && dfn="network-manager"
	echo "$dfn"
    else
	[ ${raspiosver} -ge 12 ] && echo "network-manager" || echo "dhcpcd"
    fi
}

function cfgdhcpwifi() {
    #
    # call this after any wpa has been copied into $assetdir
    #
    if [ "$wpa" != "" ]
    then
	if [ -f $assetdir/dhcpcd-wpa ]
	then
            IFS="=" read a wificountry <<< $(grep 'country=' /etc/wpa_supplicant/wpa_supplicant.conf)
	else
	    logtoboth "? Plugin $pfx: Cannot find $assetdir/dhcpcd-wpa"
	fi
    else
	if [ "$wifissid" != "" -a "$wifipassword" != "" -a "$wificountry" != "" ]
	then
	    logtoboth "> Plugin $pfx: Create /etc/wpa_supplicant/wpa_supplicant.conf"
	    logtoboth "  with SSID: $wifissid Password: $wifipassword WiFi Country: $wificountry"
	    cat > $assetdir/dhcpcd-wpa <<EOF
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
country=$wificountry
update_config=1
ap_scan=1

network={
    priority=10
    ssid="$wifissid"
    psk="$wifipassword"
}
EOF
	    logtoboth "> Plugin $pfx: Set WiFi Country '$wificountry' for FirstBoot"
	    writeconfig    # Update config to save updated wificountry
	else
	    if [ "$nowifi" != "y" ]
	    then
		logtoboth "% Plugin $pfx: Some WiFi settings not configured or no wpa: wifissid wifipassword wificountry"
		logtoboth "  If you did not configure WiFi another way the WiFi network will not connect"
	    fi
	fi
    fi
}

function getwififromwpa() {
    if [ -f $assetdir/dhcpcd-wpa ]
    then
	[ "$wifissid" == "" ] && IFS="=" read a wifissid <<< $(grep 'ssid==' $assetdir/dhcpcd-wpa)
	[ "$wifipassword" == "" ] && IFS="=" read a wifipassword <<< $(grep 'password=' $assetdir/dhcpcd-wpa)
	[ "$wificountry" == "" ] && IFS="=" read a wificountry <<< $(grep 'country=' $assetdir/dhcpcd-wpa)
    fi
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
assetdir="$SDMPT/etc/sdm/assets/network"

vldargs="|netman|dhcpcdwait|dhcpcdappend|ssh|wpa|wifissid|wifipassword|wificountry|noipv6|nmconf|nmconn|nowifi|"
rqdargs=""

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    #logtoboth "* Plugin $pfx: Start Phase 0"

    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    [ -v nowifi ] && nowifi=y
    mkdir -p $assetdir
    netman=$(getdefnm "$netman")
    logtoboth "> Plugin $pfx: Configuring '$netman' for network configuration management"

    if [ "$wpa" != "" ]
    then
	if [ -f $wpa ]
	then
	    logtoboth "> Plugin $pfx: Copy wpa_supplicant config file '$wpa' to $assetdir/dhcpcd-wpa"
	    tr -d '\r' < $wpa > $assetdir/dhcpcd-wpa
	else
	    logtoboth "? Plugin $pfx: wpa file '$wpa' not found"
	fi
    fi
    case "${netman}" in
	dhcpcd)
	    if [ "$dhcpcdappend" != "" ]
	    then
		if [ -f $dhcpcdappend ]
		then
		    logtoboth "> Plugin $pfx: Copy dhcpcdappend file '$dhcpcdappend' to $assetdir/dhcpcd-append.conf"
		    cp $dhcpcdappend $assetdir/dhcpcd-append.conf
		else
		    logtoboth "? Plugin $pfx: dhcpcdappend file '$dhcpcdappend' not found"
		fi
	    fi
	    cfgdhcpwifi
	    ;;
	nm|network-manager)
	    [ "$wificountry" == "" -o "$wifissid" == "" -o "$wifipassword" == "" ] && getwififromwpa
	    if [ "$wificountry" == "" -o "$wifissid" == "" -o "$wifipassword" == "" ]
	    then
		if [ "$nowifi" != "y" ]
		then
		    logtoboth "% Plugin $pfx: Network Manager requires explicit WiFi configuration via arguments: wifissid wifipassword wificountry"
		    logtoboth "  If you did not configure WiFi via 'nmconn' the WiFi network will not connect"
		fi
	    fi
	    for conf in nmconf nmconn
	    do
		if [ "${!conf}" != "" ]
		then
		    IFS="," read -a citems <<< "${!conf}"
		    for c in "${citems[@]}"
		    do
			if [ -f $c ]
			then
			    cbn=$(basename $c)
			    logtoboth "> Plugin $pfx: Copy $conf '$c' to $assetdir"
			    cp $c $assetdir/$conf-$cbn
			else
			    logtoboth "% Plugin $pfx: $conf file '$c' not found"
			fi
		    done
		fi
	    done
	    ;;
    esac
    
    #logtoboth "* Plugin $pfx: Complete Phase 0"

elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    netman=$(getdefnm "$netman")
    #logfreespace "at start of Plugin $pfx Phase 1"

    #logfreespace "at end of $pfx Phase 1"
    logtoboth "* Plugin $pfx: Complete Phase 1"
else
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    #xwificountry="$wificountry"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    [ -v nowifi ] && nowifi=y
    netman=$(getdefnm "$netman")
    # Figure out wifi country. command line wpa overrides settings here atm
    #[ "$wificountry" == "" ] && wificountry="$xwificountry"
    plugin_printkeys
    #logfreespace "at start of Plugin $pfx Phase post-install"
    #
    # Set ssh
    # If ssh not specifed, default to enabled
    #
    [ ! -v ssh -o "$ssh" == "" ] && ssh="service"
    dosshsetup "$ssh" network

    case "${netman}" in
	dhcpcd)
	    logtoboth "> Plugin $pfx: Set network management to dhcpcd and disable NetworkManager"
	    [ "$raspiosver" -ge 12 ] && pkg="dhcpcd" || pkg="dhcpcd5"
	    ! ispkginstalled $pkg && doaptrpterror "install --no-install-recommends --yes $pkg" $showapt
	    systemctl disable NetworkManager > /dev/null 2>&1
	    if [ -f $assetdir/dhcpcd-wpa ]
	    then
		logtoboth "> Plugin $pfx: Copy $assetdir/dhcpcd-wpa to /etc/wpa_supplicant/wpa-supplicant.conf"
		cp $assetdir/dhcpcd-wpa /etc/wpa_supplicant/wpa_supplicant.conf
		setfileownmode /etc/wpa_supplicant/wpa_supplicant.conf
	    else
		logtoboth "? Cannot find $assetdir/dhcpcd-wpa":
	    fi
	    if [ -f $assetdir/dhcpcd-append.conf ]
	    then
		logtoboth "> Plugin $pfx: Append $assetdir/dhcpcd-append.conf to /etc/dhcpcd.conf"
		cat $assetdir/dhcpcd-append.conf >> /etc/dhcpcd.conf
		[ -v noipv6 ] && echo "noipv6" >> /etc/dhcpcd.conf
	    fi
	    #
	    # Set dhcpcd wait if requested
	    #
	    if [ -v dhcpcdwait ]
	    then
		mkdir -p /etc/systemd/system/dhcpcd.service.d/
		# use the same /path/to/dhcpcd that the dhcpcd service is
		dex=$(grep -E "ExecStart=.*/dhcpcd" /lib/systemd/system/dhcpcd.service| head -n 1 -)
		dhcf=${dex##ExecStart=}  #Strip leading ExecStart=
		dhcf=${dhcf%% *}         #Strip everything after the path (switches,etc)
		logtoboth "> Plugin $pfx: Enable dhcpcd [$dhcf] 'wait for network connection'"
		cat > /etc/systemd/system/dhcpcd.service.d/wait.conf << EOF
[Service]
ExecStart=
ExecStart=$dhcf -q -w
EOF
	    fi
	    #
	    # Fix dhcpcd hooks if needed
	    #
	    if [ ! -f /lib/dhcpcd/dhcpcd-hooks/10-wpa_supplicant ]
	    then
		if [ -f /usr/share/dhcpcd/hooks/10-wpa_supplicant ]
		then
		    logtoboth "> Plugin $pfx: Copy /usr/share/dhcpcd/hooks/10-wpa_supplicant to /lib/dhcpcd/dhcpcd-hooks (BUG)"
		    cp -a /usr/share/dhcpcd/hooks/10-wpa_supplicant /lib/dhcpcd/dhcpcd-hooks
		else
		    logtoboth "% Plugin $pfx: /lib/dhcpcd/dhcp-hooks/10-wpa_supplicant not found. WiFi will not work"
		fi
	    fi
	    ;;

	nm|network-manager)
	    logtoboth "> Plugin $pfx: Set network manager to NetworkManager"
	    ! ispkginstalled network-manager && doaptrpterror "install --no-install-recommends --yes network-manager" $showapt
	    systemctl -q enable NetworkManager > /dev/null 2>&1
	    systemctl -q disable dhcpcd > /dev/null 2>&1
	    [ "$wificountry" == "" -o "$wifissid" == "" -o "$wifipassword" == "" ] && getwififromwpa
	    if [ "$wifissid" != "" -a "$wifipassword" != "" -a "$wificountry" != "" ]
	    then
		logtoboth "> Plugin $pfx: Create NetworkManager WiFi configuration"
		logtoboth "               with SSID: '$wifissid' Password: '$wifipassword' WiFi Country: '$wificountry'"
		wificname=${wifissid,,}
		cat >> /etc/sdm/0piboot/060-nm-config.sh <<EOF
#!/bin/bash
nmcli c add type wifi con-name $wificname ifname wlan0 ssid $wifissid
nmcli c modify $wificname wifi-sec.key-mgmt wpa-psk wifi-sec.psk $wifipassword
EOF
		if [ -v noipv6 ]
		then
		    echo "nmcli c modify $wificname ipv6.method disabled" >> /etc/sdm/0piboot/060-nm-config.sh
		    echo "nmcli c modify Wired\ connection\ 1 ipv6.method disabled" >> /etc/sdm/0piboot/060-nm-config.sh
		fi
	    fi
	    for conf in nmconf nmconn
	    do
		if compgen -G "$assetdir/${conf}-*" > /dev/null
		then
		    [ "$conf" == "nmconf" ] && tgt="conf.d" || tgt="system-connections"
		    for c in $assetdir/${conf}-*
		    do
			cbn=$(basename $c)
			sbn=${cbn#${conf}-}
			logtoboth "> Plugin $pfx: Copy ${conf} '$sbn' from $assetdir to /etc/NetworkManager/$tgt"
			cp $c /etc/NetworkManager/$tgt/$sbn
		    done
		fi
	    done
	    ;;
    esac
    # Don't think this is needed, but keeping jic
    #logtoboth "> Plugin $pfx: Update regulatory database"
    #update-alternatives --set regulatory.db /lib/firmware/regulatory.db-upstream
    #logfreespace "at end of $pfx Custom Phase post-install"
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
