#!/bin/bash
#
# This is an sdm plugin for: sample
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
vldargs="|toml|"
rqdargs="|toml|"
assetdir="$SDMPT/etc/sdm/assets/$pfx"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs" || exit
    #
    # Print the keys found (example usage). plugin_getargs returns the list of found keys in $foundkeys
    #
    plugin_printkeys
    [ ! -f $toml ] && logtobothex "? Plugin $pfx: toml file '$toml' not found"
    mkdir -p $SDMPT/etc/pihole
    logtoboth "> Plugin $pfx: Copy toml file to $SDMPT/etc/pihole/pihole.toml"
    cp $toml $SDMPT/etc/pihole/pihole.toml
    
    logtoboth "* Plugin $pfx: Complete Phase 0"
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    logtoboth "> Plugin $pfx: Install Pi-hole"
    logtoboth "  ** Ignore error when installer attempts to restart pihole-FTL"
    curl -sSL https://install.pi-hole.net | bash /dev/stdin --unattended
    logtoboth "> Plugin $pfx: Update pihole-FTL services to fix Pihole installer issue"
    rm -f /etc/init.d/pihole-FTL /etc/systemd/system/pihole-FTL.service
    # VV install line from pihole installer 
    install -T -m 0644 "/etc/.pihole/advanced/Templates/pihole-FTL.systemd" '/etc/systemd/system/pihole-FTL.service'
    logtoboth "> Plugin $pfx: Disable Pi-hole service"
    systemctl -q disable pihole-FTL.service
    logtoboth "> Plugin $pfx: Update list of ad-serving domains; Pihole installer skips this step"
    pihole updateGravity
    logtoboth "* Plugin $pfx: Complete Phase 1"
elif [ "$phase" == "post-install" ]
then
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
