#!/bin/bash
#
# This is an sdm plugin for: runcommand
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#
# NOTE: Forked from runscript. Fixes here likely need fixing there
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

function do_runscript() {
    #
    # $1: User-provided Script name
    # $2: user to run under
    # $3: Current phase
    local thisscript="$1" thisuser="$2" thisphase="$3"
    local line runphase rundir user script stdout stderr savehost
    local xdo="" xo="root" xu="" xdir="$assetdir" cdcmd="" docmd="" mdir=""
    #IFS="|" read script runphase rundir user stdout stderr < $assetdir/$thisscript-$thisuser-info
    IFS="|" read script runphase rundir user stdout stderr < $assetdir/$sbn-info
    [ "$user" == "$thisuser" ] || logtobothex "? Plugin $pfx: Internal error '$thisuser' <> '$user'"
    if [[ "$runphase" == "$thisphase" ]]
    then
	savehost=$(hostname)
	if [ "$user" != "" ]
	then
	    [ "$(getent passwd $user)" == "" ] && logtobothex "? Plugin $pfx: User '$user' not found"
	    xu=" as user '$user'"
	    xdo="sudo -i -u $user"
	    xo="$user"
	    hostname $thishost
	fi
	if [ "$rundir" != "" ]
	then
	    if [ ! -d $rundir ]
	    then
		logtoboth "> Plugin $pfx: Create directory $rundir"
		mkdir -p $rundir
		setfileownmode $rundir 0755 $xo:$xo
	    fi
	    xdir="$rundir"
	else
	    rundir=$assetdir
	fi
	[[ "$user" != "" ]] && [[ "$rundir" != "" ]] && docmd="bash -c \"pushd $rundir ; /tmp/$script $thisphase; \"" || docmd="/tmp/$script $thisphase"
	[ "$stdout" == "" ] && stdout="$xdir/$script.out"
	[ "$stderr" == "" ] && stderr="$xdir/$script.error"
	cp $assetdir/$script /tmp
	[ "$user" != "" ] && setfileownmode /tmp/$script 0755 $xo:$xo
	[ "$rundir" != "$assetdir" ] && mdir=" in directory '$rundir'"
	logtoboth "> Plugin $pfx: Run script '$script'${xu}${mdir}"
	echo "[ Run script $script${xu} at $(date +"%Y-%m-%d") ]" >>$stdout
	echo "" >> $stdout
	echo "[ Run script $script${xu} at $(date +"%Y-%m-%d") ]" >>$stderr
	echo "" >> $stderr
	pushd $rundir >/dev/null
	${xdo} eval "$docmd" >>$stdout 2>>$stderr || logtobothex "? Plugin $pfx: Script $script exited with error"
	popd >/dev/null
	hostname $savehost
    fi
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
allargs="$2"
loadparams
vldargs="|dir|runphase|command|user|stdout|stderr|"
rqdargs="|command|"
assetdir="$SDMPT/etc/sdm/assets/runcommand"
ucdatefmt="+%Y-%m-%d%H%M%S.%N"
mkdir -p $assetdir
mkdir -p $assetdir/completed

[ "$user" == "" ] && user=root
[ "$runphase" == "" ] && runphase="1"
sbn="$user-$runphase"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$allargs" "$vldargs" "$rqdargs" || exit
    plugin_printkeys
    [[ "1|post-install" =~ "$runphase" ]] || logtobothex "? Plugin $pfx: Phase '$runphase' not recognized"
    logtoboth "* Plugin $pfx: Complete Phase 0"
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$allargs" "$vldargs" "$rqdargs"
    plugin_printkeys
    if [ "$runphase" == "$phase" ]
    then
	printf "#!/bin/bash\n$command\n" > $assetdir/$sbn
	chmod 755 $assetdir/$sbn
	echo "$sbn|$runphase|$dir|$user|$stdout|$stderr|" >> $assetdir/$sbn-info
	do_runscript $sbn $user "$phase"
	mv $assetdir/$sbn-info $assetdir/completed/$sbn-info-$(date "$ucdatefmt")
    fi
    logtoboth "* Plugin $pfx: Complete Phase 1"
else
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$allargs" "$vldargs" "$rqdargs"
    plugin_printkeys
    if [ "$runphase" == "$phase" ]
    then
	printf "#!/bin/bash\n$command\n" > $assetdir/$sbn
	chmod 755 $assetdir/$sbn
	echo "$sbn|$runphase|$dir|$user|$stdout|$stderr|" >> $assetdir/$sbn-info
	do_runscript $sbn $user "$phase"
	mv $assetdir/$sbn-info $assetdir/completed/$sbn-info-$(date "$ucdatefmt")
    fi
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
