#!/bin/bash
#
# This is an sdm plugin for: swap
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
vldargs="|config|filesize|zramsize|"
rqdargs=""                   # |list|of|required|args|or|nullstring|
assetdir="$SDMPT/etc/sdm/assets/$pfx"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs" || exit
    plugin_printkeys
    mkdir -p $assetdir
    if [ "$config" != "" ]
    then
	[ -f $config ] || logtobothex "? Plugin $pfx: Config file '$config' not found"
    fi
    cp $config $assetdir
    logtoboth "* Plugin $pfx: Complete Phase 0"
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #logfreespace "at start of Plugin $pfx Phase 1"
    mkdir -p /etc/rpi/swap.conf.d
    if [ "$config" != "" ]
    then
	cfasset=$assetdir/$(basename $config)
	[ -f $cfasset ] || logtobothex "? Plugin $pfx: Config file '$cfasset' disappeared"
	logtoboth "> Plugin $pfx: Copy config file '$cfasset' to '/etc/rpi/swap.conf.d'"
	cp $cfasset /etc/rpi/swap.conf.d
    fi
    if [ "$filesize" != "" ]
    then
	logtoboth "> Plugin $pfx: Configure swap file size '$filesize'"
	printf "[File]\nFixedSizeMiB=%s\n" $filesize >> /etc/rpi/swap.conf.d/90-sdm-config
    fi
    if [ "$zramsize" != "" ]
    then
	logtoboth "> Plugin $pfx: Configure zram file size '$zramsize'"
	printf "[Zram]\nFixedSizeMiB=%s\n" $zramsize >> /etc/rpi/swap.conf.d/90-sdm-config
    fi
    #logfreespace "at end of $pfx Phase 1"
    logtoboth "* Plugin $pfx: Complete Phase 1"
elif [ "$phase" == "post-install" ]
then
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    #logfreespace "at start of Plugin $pfx Phase post-install"

    #logfreespace "at end of $pfx Custom Phase post-install"
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
