#!/bin/bash
#
# This is an sdm plugin for: sample
#
# The plugin is called three times: for Phase 0, Phase 1, and post-install.
#

function loadparams() {
    source $SDMPT/etc/sdm/sdm-readparams
}

# $1 is the phase: "0", "1", or "post-install"
# $2 is the argument list: arg1=val1|arg2=val2|arg3=val3| ...
#
# Main code for the Plugin
#
phase=$1
pfx="$(basename $0)"     #For messages
args="$2"
loadparams
vldargs="|apps|dm|nodmconsole|wm|"
rqdargs=""                   # |list|of|required|args|or|nullstring|
assetdir="$SDMPT/etc/sdm/assets/$pfx"

if [ "$phase" == "0" ]
then
    #
    # In Phase 0 all references to directories in the image must be preceded by $SDMPT
    #
    logtoboth "* Plugin $pfx: Start Phase 0"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs" || exit
    plugin_printkeys
    mkdir -p $assetdir
    if [ "$dm" != "" ]
    then
	[[ "lightdm|wdm|xdm" =~ "$dm" ]] || logtoboth "% Plugin $pfx: Unrecognized display manager '$dm'; no boot behavior handling done"
    fi
    name=x11-apps
    if [ "$apps" != "" ]
    then
        appfile=$(findappfile "$apps")
        exitiferr "$appfile"
	apps=$(getapplist "$appfile")
	if [ "$apps" != "" ]
	then
	    if [ -f $assetdir/$name ]
	    then
		read oapps < $assetdir/$name
		apps="$oapps $apps"
		fd=$(date -d "$(stat --printf "%y" $assetdir/$name)" +$sdatefmt)
		logtoboth "> Plugin $pfx: Save prior 'apps' list '$name' as '$name-$fd'"
		mv $assetdir/$name $assetdir/$name-$fd
	    fi
	    echo "$apps" >| $assetdir/$name
	    logtoboth "> Plugin $pfx [$name]: Saved 'apps' list: $apps"
	fi
    fi
    logtoboth "* Plugin $pfx: Complete Phase 0"
elif [ "$phase" == "1" ]
then
    #
    # Phase 1 (in nspawn)
    #
    logtoboth "* Plugin $pfx: Start Phase 1"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    logfreespace "at start of Plugin $pfx Phase 1"
    [ -v nodmconsole ] && nodmconsole=yes || nodmconsole=no
    basefonts="xfonts-base xfonts-100dpi xfonts-75dpi xfonts-scalable"
    [ -f $assetdir/x11-apps ] && read svapps < $assetdir/x11-apps
    if [ ! -x /bin/Xorg ]
    then
	x11pkgs="xserver-xorg xserver-xorg-core xserver-common gldriver-test x11-apps x11-xserver-utils $basefonts $dm $wm $svapps"
	doinstalls "$x11pkgs" "X11 Install"
    fi
    
    logfreespace "at end of $pfx Phase 1"
    logtoboth "* Plugin $pfx: Complete Phase 1"
elif [ "$phase" == "post-install" ]
then
    #
    # Plugin Post-install edits
    #
    logtoboth "* Plugin $pfx: Start Phase post-install"
    plugin_getargs $pfx "$args" "$vldargs" "$rqdargs"
    [ -v nodmconsole ] && nodmconsole=yes
    [[ "$dm" == "" ]] || [[ "$wm" == "" ]] && nodmconsole=yes

    gfxcfgpostinstall $nodmconsole
    logtoboth "* Plugin $pfx: Complete Phase post-install"
fi
